version: '3'
services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: npm run dev

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myfinances
      POSTGRES_PASSWORD: mfinances
      POSTGRES_DB: myfinances_dev
    volumes:
      - db-myfinances:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-myfinances:  # Define o volume chamado "db-myfinances"

